name: Continuous Training

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 8 * * *"

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Train model
        run: python train.py
      - name: Commit model artifact
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(model): update diabetes_model.pkl"
          file_pattern: models/diabetes_model.pkl
